name: generate-site
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v31.5.2
      - name: Install direnv
        run: |
          nix profile add nixpkgs#direnv
      - name: Open direnv shell
        run: |
          direnv allow .
          direnv export gha > "$GITHUB_ENV"

      - name: Generate
        run: |
          daisy build
          echo "yesimhuman.dev" > site/CNAME

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
