name: generate-site
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
      - name: "Setup environment"
        uses: JRMurr/direnv-nix-action@4.2.0

      - name: Generate
        shell: bash
        run: -|
          mkdir site
          mv placeholder.htm site/index.htm
          echo "yesimhuman.dev" > site/CNAME

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
